# Changes here will be overwritten by Copier
_commit: v0.1.0a2
_src_path: gh:reservoir-data/singer-tap-copier-template
author_email: edgarrmondragon@hey.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.12'
repository_name: tap-hookdeck
repository_namespace: edgarrmondragon
repository_provider: github.com
repository_visibility: public
tap_auth_method: API Key
tap_id: tap-hookdeck
tap_package_command_line_name: tap-hookdeck
tap_package_distribution_name: tap-hookdeck
tap_package_import_name: tap_hookdeck
tap_source_description: Receive, process, and deliver messages across your event-driven
    architecture
tap_source_id: Hookdeck
tap_source_name: Hookdeck
tap_stream_type: REST
vscode_files: true
