name: Test tap-hookdeck

on:
  push:
    branches: [main]
    paths:
      - tap_hookdeck/**
      - tests/**
      - pyproject.toml
      - tox.ini
      - uv.lock
      - .github/workflows/test.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - tap_hookdeck/**
      - tests/**
      - pyproject.toml
      - tox.ini
      - uv.lock
      - .github/workflows/test.yml
  workflow_dispatch:
  schedule:
  # Run weekly on Monday at 12:00 PM UTC
  - cron: "0 12 * * 1"

env:
  FORCE_COLOR: "1"
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.6.10
  # renovate: datasource=pypi depName=tox
  TOX_VERSION: 4.25.0
  # renovate: datasource=pypi depName=tox-uv
  TOX_UV_VERSION: 1.25.0

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        include:
        - { environment: "dependencies", python-version: "3.x" }
        - { environment: "typing",       python-version: "3.x" }

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1
      with:
        version: ${{ env.UV_VERSION }}
    - name: Run tests
      env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        TAP_HOOKDECK_API_KEY: ${{ secrets.TAP_HOOKDECK_API_KEY }}
        TAP_HOOKDECK_START_DATE: ${{ secrets.TAP_HOOKDECK_START_DATE }}
      run: >
        uvx
        --with tox-uv==${{ env.TOX_UV_VERSION }}
        --with tox==${{ env.TOX_VERSION }}
        tox -e ${{ matrix.environment || matrix.python-version }}
